version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            EC2_USERNAME=ubuntu
            # TODO Change to your server's URL or public IP
            EC2_PUBLIC_DNS=ec2-18-184-3-98.eu-central-1.compute.amazonaws.com
            scp C:\Users\LENOVO\Desktop\circleci-example ubuntu@ec2-35-158-2-108.eu-central-1.compute.amazonaws.com:\home\ubuntu\

