version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "67:02:50:27:32:6c:a1:e1:25:3f:0d:72:e5:2d:2c:7e"
      - run:
      name: Deploy
      command: |
        EC2_USERNAME=ubuntu
        # TODO Change to your server's URL or public IP
        EC2_PUBLIC_DNS=ec2-35-158-2-108.eu-central-1.compute.amazonaws.com
        scp C:\Users\LENOVO\Desktop\circleci-example ubuntu@ec2-35-158-2-108.eu-central-1.compute.amazonaws.com:\home\ubuntu\